### ISSUE TITLE
ConcatenatingAudioSource.clear()

### ISSUE THREAD

**Issue by zyk-miao** [bleonard252/just_audio_mpv#5]
when ConcatenatingAudioSource is not empty ConcatenatingAudioSource.clear() will throw "error running command".
I use ConcatenatingAudioSource.clear and ConcatenatingAudioSource.addAll change playing list.

**Comment by zyk-miao** [comment]
![图片](https://user-images.githubusercontent.com/45023244/222658670-22975d7c-78de-4658-8fdd-67f577ce1aae.png)

**Comment by zyk-miao** [comment]
I call player.pause before  ConcatenatingAudioSource.clear avoid "error running command".

**Comment by bleonard252** [comment]
Try using this in your `pubspec.yaml` and running `flutter pub get`:
```yaml
dependencies:
  ...
  just_audio_mpv:
    git: https://github.com/bleonard252/just_audio_mpv
    ref: 5-concatenatingaudiosource
```
This will use an unpublished version of the package made to test a fix to this issue. Does it fix the problem? Does it cause any new problems (i.e. removing the wrong item from a playlist)?
